/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import type { TypedEventFilter, TypedEvent, TypedListener } from './common'

interface L1TokenBridgeRetryableSenderInterface extends ethers.utils.Interface {
  functions: {
    'initialize()': FunctionFragment
    'owner()': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'sendRetryableUsingEth((address,address,address,address,uint256,uint256),(address,address,address,address,address,address),(address,address,address,address,address),address,address,address,address)': FunctionFragment
    'sendRetryableUsingFeeToken((address,address,address,address,uint256,uint256),(address,address,address,address,address,address),(address,address,address,address,address),address,address,address)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'initialize', values?: undefined): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'sendRetryableUsingEth',
    values: [
      {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      string,
      string,
      string,
      string
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'sendRetryableUsingFeeToken',
    values: [
      {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      string,
      string,
      string
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string]
  ): string

  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'sendRetryableUsingEth',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'sendRetryableUsingFeeToken',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result

  events: {
    'Initialized(uint8)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'Initialized'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
}

export type InitializedEvent = TypedEvent<[number] & { version: number }>

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>

export class L1TokenBridgeRetryableSender extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: L1TokenBridgeRetryableSenderInterface

  functions: {
    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    owner(overrides?: CallOverrides): Promise<[string]>

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    sendRetryableUsingEth(
      retryableParams: {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      l2: {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      l1: {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      l2StandardGatewayAddress: string,
      rollupOwner: string,
      deployer: string,
      aliasedL1UpgradeExecutor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    sendRetryableUsingFeeToken(
      retryableParams: {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      l2: {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      l1: {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      l2StandardGatewayAddress: string,
      rollupOwner: string,
      aliasedL1UpgradeExecutor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>
  }

  initialize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  owner(overrides?: CallOverrides): Promise<string>

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  sendRetryableUsingEth(
    retryableParams: {
      inbox: string
      target: string
      excessFeeRefundAddress: string
      callValueRefundAddress: string
      maxGas: BigNumberish
      gasPriceBid: BigNumberish
    },
    l2: {
      routerTemplate: string
      standardGatewayTemplate: string
      customGatewayTemplate: string
      wethGatewayTemplate: string
      wethTemplate: string
      upgradeExecutorTemplate: string
    },
    l1: {
      router: string
      standardGateway: string
      customGateway: string
      wethGateway: string
      weth: string
    },
    l2StandardGatewayAddress: string,
    rollupOwner: string,
    deployer: string,
    aliasedL1UpgradeExecutor: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  sendRetryableUsingFeeToken(
    retryableParams: {
      inbox: string
      target: string
      excessFeeRefundAddress: string
      callValueRefundAddress: string
      maxGas: BigNumberish
      gasPriceBid: BigNumberish
    },
    l2: {
      routerTemplate: string
      standardGatewayTemplate: string
      customGatewayTemplate: string
      wethGatewayTemplate: string
      wethTemplate: string
      upgradeExecutorTemplate: string
    },
    l1: {
      router: string
      standardGateway: string
      customGateway: string
      wethGateway: string
      weth: string
    },
    l2StandardGatewayAddress: string,
    rollupOwner: string,
    aliasedL1UpgradeExecutor: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    initialize(overrides?: CallOverrides): Promise<void>

    owner(overrides?: CallOverrides): Promise<string>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    sendRetryableUsingEth(
      retryableParams: {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      l2: {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      l1: {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      l2StandardGatewayAddress: string,
      rollupOwner: string,
      deployer: string,
      aliasedL1UpgradeExecutor: string,
      overrides?: CallOverrides
    ): Promise<void>

    sendRetryableUsingFeeToken(
      retryableParams: {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      l2: {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      l1: {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      l2StandardGatewayAddress: string,
      rollupOwner: string,
      aliasedL1UpgradeExecutor: string,
      overrides?: CallOverrides
    ): Promise<void>

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>
  }

  filters: {
    'Initialized(uint8)'(
      version?: null
    ): TypedEventFilter<[number], { version: number }>

    Initialized(version?: null): TypedEventFilter<[number], { version: number }>

    'OwnershipTransferred(address,address)'(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >
  }

  estimateGas: {
    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    sendRetryableUsingEth(
      retryableParams: {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      l2: {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      l1: {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      l2StandardGatewayAddress: string,
      rollupOwner: string,
      deployer: string,
      aliasedL1UpgradeExecutor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    sendRetryableUsingFeeToken(
      retryableParams: {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      l2: {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      l1: {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      l2StandardGatewayAddress: string,
      rollupOwner: string,
      aliasedL1UpgradeExecutor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    sendRetryableUsingEth(
      retryableParams: {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      l2: {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      l1: {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      l2StandardGatewayAddress: string,
      rollupOwner: string,
      deployer: string,
      aliasedL1UpgradeExecutor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    sendRetryableUsingFeeToken(
      retryableParams: {
        inbox: string
        target: string
        excessFeeRefundAddress: string
        callValueRefundAddress: string
        maxGas: BigNumberish
        gasPriceBid: BigNumberish
      },
      l2: {
        routerTemplate: string
        standardGatewayTemplate: string
        customGatewayTemplate: string
        wethGatewayTemplate: string
        wethTemplate: string
        upgradeExecutorTemplate: string
      },
      l1: {
        router: string
        standardGateway: string
        customGateway: string
        wethGateway: string
        weth: string
      },
      l2StandardGatewayAddress: string,
      rollupOwner: string,
      aliasedL1UpgradeExecutor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>
  }
}
