"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArbosActs__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "CallerNotArbOS",
        type: "error",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "batchTimestamp",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "batchPosterAddress",
                type: "address",
            },
            {
                internalType: "uint64",
                name: "batchNumber",
                type: "uint64",
            },
            {
                internalType: "uint64",
                name: "batchDataGas",
                type: "uint64",
            },
            {
                internalType: "uint256",
                name: "l1BaseFeeWei",
                type: "uint256",
            },
        ],
        name: "batchPostingReport",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "l1BaseFee",
                type: "uint256",
            },
            {
                internalType: "uint64",
                name: "l1BlockNumber",
                type: "uint64",
            },
            {
                internalType: "uint64",
                name: "l2BlockNumber",
                type: "uint64",
            },
            {
                internalType: "uint64",
                name: "timePassed",
                type: "uint64",
            },
        ],
        name: "startBlock",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class ArbosActs__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ArbosActs__factory = ArbosActs__factory;
ArbosActs__factory.abi = _abi;
