"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Bytes32ERC20WithMetadata__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        name: "allowance",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "guy",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "wad",
                type: "uint256",
            },
        ],
        name: "approve",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        name: "balanceOf",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "decimals",
        outputs: [
            {
                internalType: "uint8",
                name: "",
                type: "uint8",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "mint",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "name",
        outputs: [
            {
                internalType: "bytes32",
                name: "",
                type: "bytes32",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "symbol",
        outputs: [
            {
                internalType: "bytes32",
                name: "",
                type: "bytes32",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "dst",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "wad",
                type: "uint256",
            },
        ],
        name: "transfer",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "src",
                type: "address",
            },
            {
                internalType: "address",
                name: "dst",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "wad",
                type: "uint256",
            },
        ],
        name: "transferFrom",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
const _bytecode = "0x60806040526426b0b5b2b960d91b6002556226a5a960e91b6003556004805460ff1916601217905534801561003357600080fd5b50610312806100436000396000f3fe608060405234801561001057600080fd5b50600436106100835760003560e01c806306fdde0314610088578063095ea7b3146100a25780631249c58b146100e257806323b872dd146100ec578063313ce5671461012257806370a082311461014057806395d89b4114610166578063a9059cbb1461016e578063dd62ed3e1461019a575b600080fd5b6100906101c8565b60408051918252519081900360200190f35b6100ce600480360360408110156100b857600080fd5b506001600160a01b0381351690602001356101ce565b604080519115158252519081900360200190f35b6100ea6101f8565b005b6100ce6004803603606081101561010257600080fd5b506001600160a01b03813581169160208101359091169060400135610217565b61012a61028a565b6040805160ff9092168252519081900360200190f35b6100906004803603602081101561015657600080fd5b50356001600160a01b0316610293565b6100906102a5565b6100ce6004803603604081101561018457600080fd5b506001600160a01b0381351690602001356102ab565b610090600480360360408110156101b057600080fd5b506001600160a01b03813581169160200135166102bf565b60025481565b3360009081526001602081815260408084206001600160a01b039690961684529490529290205590565b3360009081526020819052604090208054670de0b6b3a7640000019055565b60006001600160a01b0384163314610254576001600160a01b03841660009081526001602090815260408083203384529091529020805483900390555b506001600160a01b0392831660009081526020819052604080822080548490039055929093168352912080549091019055600190565b60045460ff1681565b60006020819052908152604090205481565b60035481565b60006102b8338484610217565b9392505050565b60016020908152600092835260408084209091529082529020548156fea264697066735822122043d4effd14d9c7244a7a35fbf4f3d619ec09fd4d3745cb83ee2547d43676f3ef64736f6c634300060b0033";
const isSuperArgs = (xs) => xs.length > 1;
class Bytes32ERC20WithMetadata__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
        this.contractName = "Bytes32ERC20WithMetadata";
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.Bytes32ERC20WithMetadata__factory = Bytes32ERC20WithMetadata__factory;
Bytes32ERC20WithMetadata__factory.bytecode = _bytecode;
Bytes32ERC20WithMetadata__factory.abi = _abi;
