"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICustomGateway__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "address",
                name: "l1Address",
                type: "address",
            },
            {
                indexed: true,
                internalType: "address",
                name: "l2Address",
                type: "address",
            },
        ],
        name: "TokenSet",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "_l1Token",
                type: "address",
            },
        ],
        name: "l1ToL2Token",
        outputs: [
            {
                internalType: "address",
                name: "_l2Token",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class ICustomGateway__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ICustomGateway__factory = ICustomGateway__factory;
ICustomGateway__factory.abi = _abi;
