"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IGasRefunder__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address payable",
                name: "spender",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "gasUsed",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "calldataSize",
                type: "uint256",
            },
        ],
        name: "onGasSpent",
        outputs: [
            {
                internalType: "bool",
                name: "success",
                type: "bool",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IGasRefunder__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IGasRefunder__factory = IGasRefunder__factory;
IGasRefunder__factory.abi = _abi;
