"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NodeInterfaceDebug__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "ticket",
                type: "bytes32",
            },
        ],
        name: "getRetryable",
        outputs: [
            {
                components: [
                    {
                        internalType: "uint64",
                        name: "timeout",
                        type: "uint64",
                    },
                    {
                        internalType: "address",
                        name: "from",
                        type: "address",
                    },
                    {
                        internalType: "address",
                        name: "to",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "value",
                        type: "uint256",
                    },
                    {
                        internalType: "address",
                        name: "beneficiary",
                        type: "address",
                    },
                    {
                        internalType: "uint64",
                        name: "tries",
                        type: "uint64",
                    },
                    {
                        internalType: "bytes",
                        name: "data",
                        type: "bytes",
                    },
                ],
                internalType: "struct NodeInterfaceDebug.RetryableInfo",
                name: "retryable",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class NodeInterfaceDebug__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.NodeInterfaceDebug__factory = NodeInterfaceDebug__factory;
NodeInterfaceDebug__factory.abi = _abi;
