/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers'
import { Provider, TransactionRequest } from '@ethersproject/providers'
import type { Cloneable, CloneableInterface } from '../Cloneable'

const _abi = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'isMaster',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]

const _bytecode =
  '0x6080604052348015600f57600080fd5b506000805460ff19166001179055607d8061002b6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80636f791d2914602d575b600080fd5b60005460ff16604051901515815260200160405180910390f3fea2646970667358221220632d35b8983731fa052162e024ba773f03dad873c9337cf140c00dd91b776e1964736f6c63430008110033'

export class Cloneable__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0])
    } else {
      super(...args)
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Cloneable> {
    return super.deploy(overrides || {}) as Promise<Cloneable>
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {})
  }
  attach(address: string): Cloneable {
    return super.attach(address) as Cloneable
  }
  connect(signer: Signer): Cloneable__factory {
    return super.connect(signer) as Cloneable__factory
  }
  static readonly bytecode = _bytecode
  static readonly abi = _abi
  static createInterface(): CloneableInterface {
    return new utils.Interface(_abi) as CloneableInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Cloneable {
    return new Contract(address, _abi, signerOrProvider) as Cloneable
  }
}
